transport:
  mode: udp
  feedback_interval_ms: 200
  feedback_redundancy: 10
  feedback_timeout_ms: 1000

sender:
  input: file
  connect: 10.88.0.2:9000
  video_file: /home/u20/code/jetson-2k.mp4
  camera_device: /dev/video0
  camera_width: 640
  camera_height: 480
  camera_fps: 30
  max_video_kbps: 2000

receiver:
  listen: 10.88.0.2:9000
  display: true
  minimum_output_width: 640
  minimum_output_height: 360
  minimum_output_fps: 20
  upscale_mode: lanczos_sharpen
  interpolation_mode: blend
  write_h264: true
  output_file: received.h264

latency:
  metric: encode_to_decode
  window_seconds: 10
