# CMake generated Testfile for 
# Source directory: D:/Code/C++/SRT-Weak-Network-Video
# Build directory: D:/Code/C++/SRT-Weak-Network-Video/build-clean
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[protocol_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Debug/protocol_tests.exe")
  set_tests_properties([=[protocol_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;146;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[protocol_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Release/protocol_tests.exe")
  set_tests_properties([=[protocol_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;146;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[protocol_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/MinSizeRel/protocol_tests.exe")
  set_tests_properties([=[protocol_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;146;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[protocol_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/RelWithDebInfo/protocol_tests.exe")
  set_tests_properties([=[protocol_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;146;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
else()
  add_test([=[protocol_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[frame_pacer_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Debug/frame_pacer_tests.exe")
  set_tests_properties([=[frame_pacer_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;154;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[frame_pacer_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Release/frame_pacer_tests.exe")
  set_tests_properties([=[frame_pacer_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;154;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[frame_pacer_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/MinSizeRel/frame_pacer_tests.exe")
  set_tests_properties([=[frame_pacer_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;154;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[frame_pacer_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/RelWithDebInfo/frame_pacer_tests.exe")
  set_tests_properties([=[frame_pacer_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;154;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
else()
  add_test([=[frame_pacer_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[adaptation_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Debug/adaptation_tests.exe")
  set_tests_properties([=[adaptation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;162;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[adaptation_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Release/adaptation_tests.exe")
  set_tests_properties([=[adaptation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;162;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[adaptation_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/MinSizeRel/adaptation_tests.exe")
  set_tests_properties([=[adaptation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;162;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[adaptation_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/RelWithDebInfo/adaptation_tests.exe")
  set_tests_properties([=[adaptation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;162;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
else()
  add_test([=[adaptation_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[network_quality_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Debug/network_quality_tests.exe")
  set_tests_properties([=[network_quality_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;170;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[network_quality_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Release/network_quality_tests.exe")
  set_tests_properties([=[network_quality_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;170;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[network_quality_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/MinSizeRel/network_quality_tests.exe")
  set_tests_properties([=[network_quality_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;170;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[network_quality_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/RelWithDebInfo/network_quality_tests.exe")
  set_tests_properties([=[network_quality_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;170;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
else()
  add_test([=[network_quality_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[runtime_config_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Debug/runtime_config_tests.exe")
  set_tests_properties([=[runtime_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;178;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[runtime_config_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Release/runtime_config_tests.exe")
  set_tests_properties([=[runtime_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;178;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[runtime_config_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/MinSizeRel/runtime_config_tests.exe")
  set_tests_properties([=[runtime_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;178;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[runtime_config_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/RelWithDebInfo/runtime_config_tests.exe")
  set_tests_properties([=[runtime_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;178;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
else()
  add_test([=[runtime_config_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[latency_stats_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Debug/latency_stats_tests.exe")
  set_tests_properties([=[latency_stats_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;186;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[latency_stats_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Release/latency_stats_tests.exe")
  set_tests_properties([=[latency_stats_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;186;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[latency_stats_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/MinSizeRel/latency_stats_tests.exe")
  set_tests_properties([=[latency_stats_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;186;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[latency_stats_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/RelWithDebInfo/latency_stats_tests.exe")
  set_tests_properties([=[latency_stats_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;186;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
else()
  add_test([=[latency_stats_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[output_processing_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Debug/output_processing_tests.exe")
  set_tests_properties([=[output_processing_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;198;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[output_processing_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/Release/output_processing_tests.exe")
  set_tests_properties([=[output_processing_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;198;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[output_processing_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/MinSizeRel/output_processing_tests.exe")
  set_tests_properties([=[output_processing_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;198;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[output_processing_tests]=] "D:/Code/C++/SRT-Weak-Network-Video/build-clean/RelWithDebInfo/output_processing_tests.exe")
  set_tests_properties([=[output_processing_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;198;add_test;D:/Code/C++/SRT-Weak-Network-Video/CMakeLists.txt;0;")
else()
  add_test([=[output_processing_tests]=] NOT_AVAILABLE)
endif()
subdirs("_deps/srt-build")
